
// import type { Metadata } from "next";
// import "./globals.css";
// import { Poppins, Outfit } from "next/font/google";
// import { Navbar } from "@/components/layout/navbar";
// import { Footer } from "@/components/layout/footer";

// export const metadata: Metadata = {
//   title: "DR Students",
//   description: "Generated by create next app",
// };

// const PoppinsFont = Poppins({
//   variable: "--font-poppins",
//   subsets: ["latin"],
//   weight: ["400", "700"],
// });

// const outfitFont = Outfit({
//   subsets: ["latin"],
//   weight: ["400", "700"],
//   variable: "--font-outfit",
// });

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={`${PoppinsFont.variable} ${outfitFont.variable} antialiased`}>
//         <Navbar/>
//         {/* <LoginPopup/> */}
//           {children}
//         <Footer/>
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import "./globals.css";
import { Poppins, Outfit } from "next/font/google";
import { Navbar } from "@/components/layout/navbar";
import { Footer } from "@/components/layout/footer";
import ScrollPopupWrapper from "@/components/helpers/ScrollPopupWrapper";

export const metadata: Metadata = {
  title: "DR Students",
  description: "Generated by create next app",
};

const PoppinsFont = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const OutfitFont = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${PoppinsFont.variable} ${OutfitFont.variable} antialiased`}>
        <Navbar />

        <ScrollPopupWrapper />

        {children}

        <Footer />
      </body>
    </html>
  );
}
