
import type { Metadata } from "next";
import "./globals.css";
import { Poppins, Outfit } from "next/font/google";
import { Navbar } from "@/components/layout/navbar";
import LoginPopup from "@/components/ui/loginpopup";
import { Footer } from "@/components/layout/footer";
import ClgCard from "@/components/ui/clgcard";
import ChooseYourPlan from "@/components/ui/chooseyourplan";
import WhyMembership from "@/components/ui/whymembership";
import WhatStudentsSay from "@/components/ui/whatstudentssay";
import FAQ from "@/components/ui/faq";
import StudentAbroad from "@/components/ui/studentsabroad";

export const metadata: Metadata = {
  title: "DR Students",
  description: "Generated by create next app",
};

const PoppinsFont = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const outfitFont = Outfit({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-outfit",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${PoppinsFont.variable} ${outfitFont.variable} antialiased`}>
        <Navbar/>
        {/* <LoginPopup/> */}
          {children}
        <Footer/>
      </body>
    </html>
  );
}
